### ISSUE TITLE
build error : wrong type for Mount method

### ISSUE THREAD

**Issue by monkeydri** [projectatomic/docker-lvm-plugin#14]
Following error on build :

```
monkeydri@server:~/docker-lvm-plugin$ make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
# _/home/monkeydri/docker-lvm-plugin
./main.go:65: cannot use lvm (type *lvmDriver) as type volume.Driver in argument to volume.NewHandler:
	*lvmDriver does not implement volume.Driver (wrong type for Mount method)
		have Mount(volume.Request) volume.Response
		want Mount(volume.MountRequest) volume.Response
Makefile:19: recipe for target 'lvm-plugin-build' failed
make: *** [lvm-plugin-build] Error 2
```

go-plugins-helpers/volume : latest version (commit f3a3876)
go version : 1.6
Docker version 1.10.3, build 20f81dd
os : ubuntu 16.04.1

Error is due to an update of go-plugins-helpers/volume : commit https://github.com/docker/go-plugins-helpers/commit/461a12724a063018b1c2c3ef8ca2bd87ae6d84fb has changed the structs for Mount and Unmount, therefore the functions headers must be updated (example shown by volume/api_test.go).

**Comment by shishir-a412ed** [comment]
Fixed with PR #16
