### ISSUE TITLE
installation fails with error : cannot use d (type glusterfsDriver) as type volume.Driver 

### ISSUE THREAD

**Issue by harshal-shah** [projectatomic/docker-lvm-plugin#18]
While trying to install the plugin on ubuntu 14.04 I'm getting following error: 

`
go/src/github.com/calavera/docker-volume-glusterfs/main.go:38: **cannot use d (type glusterfsDriver) as type volume.Driver in argument to volume.NewHandler:**
        glusterfsDriver does not implement volume.Driver (wrong type for Mount method)
                have Mount(volume.Request) volume.Response
                want Mount(volume.MountRequest) volume.Response
`

**Comment by shishir-a412ed** [comment]
@harshal-shah 
PR #16 should fix this problem.

Shishir

**Comment by shishir-a412ed** [comment]
This is fixed now. Closing this issue.
