### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by che** [projectatomic/docker-lvm-plugin#36]
Hi ,

 # make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
 # _/home/dev/docker-lvm-plugin
**./main.go:66: cannot use lvmPluginSocketPath (type string) as type int in argument to h.Handler.ServeUnix**
Makefile:19: recipe for target 'lvm-plugin-build' failed
make: *** [lvm-plugin-build] Error 2

 # go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dev/docker-lvm-plugin"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

On Ubuntu 16.04.

Thanks you.

**Comment by shishir-a412ed** [comment]
Works for me on Ubuntu 16.04.

````
# make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
# sudo make install
install -D -m 644 etc/docker/docker-lvm-plugin /etc/docker/docker-lvm-plugin
install -D -m 644 systemd/docker-lvm-plugin.service /usr/lib/systemd/system/docker-lvm-plugin.service
install -D -m 644 systemd/docker-lvm-plugin.socket /usr/lib/systemd/system/docker-lvm-plugin.socket
install -D -m 755 docker-lvm-plugin /usr/libexec/docker/docker-lvm-plugin
install -D -m 644 docker-lvm-plugin.8 /usr/share/man/man8/docker-lvm-plugin.8
````

````
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
````

Are you using the latest commit from the master branch ?

Shishir

**Comment by batmany13** [comment]
@shishir-a412ed I believe this broke due to this [change](https://github.com/docker/go-plugins-helpers/commit/0af5adef105c32d8ad1a58269f26a783a96d522f) in [PR 67](https://github.com/docker/go-plugins-helpers/pull/67).  "ServeUnix" changed their function signature so that the 2nd parameter is no longer a string, but an int.  A forked repo fixed this by doing this [change](https://github.com/gregoplex/docker-lvm-plugin/commit/6f1b34d0a4d7ed8438c3b39d642a241b56d71e0b)

**Comment by shishir-a412ed** [comment]
@batmany13 Please see this:
https://github.com/projectatomic/docker-lvm-plugin/issues/41#issuecomment-379565667

**Comment by shishir-a412ed** [comment]
@che @batmany13 
I have also updated the `docker-lvm-plugin` to work with latest version of `go-plugin-helpers` (Although it should work with the old version too).
Please see this: #47

**Comment by rhatdan** [comment]
Fine with me.
