### ISSUE TITLE
needs xfsprogs dependency

### ISSUE THREAD

**Issue by neurotensin** [projectatomic/docker-lvm-plugin#37]
This is simple, but I am not sure how to fix this in a golang project.

In driver.go there is 
 cmd = exec.Command("mkfs.xfs", device)
Although it sends information of failure to the log
l.logger.Err(fmt.Sprintf("Create: mkfs.xfs error: %s output %s", err, string(out)))
It only puts this on the console
 return resp(fmt.Errorf("Error partitioning volume"))

My system is debian jessie, so might be worth checking to see if xfsprogs are installed (or just check the executable).

It may save a number of distracting bug complaints...

**Comment by shishir-a412ed** [comment]
@neurotensin I think we can check the executable at plugin startup, something like:

````
if ( /sbin/mkfs.xfs does not exist) {
   Error: mkfs.xfs is not available, please install xfsprogs to continue;
}
````

@rhatdan WDYT ?

**Comment by rhatdan** [comment]
SGTM
