### ISSUE TITLE
`vendor/*` should instead be `vendor/src/*`

### ISSUE THREAD

**Issue by lsm5** [projectatomic/docker-lvm-plugin#4]
move everything inside `vendor` into `vendor/src`, otherwise rpmbuild and GOPATH seem to have trouble.

**Comment by rhatdan** [comment]
@shishir-a412ed PTAL

**Comment by shishir-a412ed** [comment]
@lsm5 @rhatdan I think this is auto generated by godeps.
@mrunalp can we move this under `vendor/src/*` manually ?

**Comment by mrunalp** [comment]
I just looked into this. Sorry about confusion but this is actually correct per the new go vendoring support. @lsm5 Are you using the makefile to build or building it yourself? You may need to set GO15VENDOREXPERIMENT=1 in your build environment.

**Comment by lsm5** [comment]
@mrunalp @shishir-a412ed thanks, I'm building it myself, I'll set the env var next build.
