### ISSUE TITLE
make not running go dependencies

### ISSUE THREAD

**Issue by rocki9satya** [projectatomic/docker-lvm-plugin#49]
When I run the make command, i get lot of errors, mainly to do with dependencies 

a.	yum install golang git golang-github-cpuguy83-go-md2man
b.	mkdir -p $HOME/go/src/github.com
c.	cd $HOME/go/src/github.com
d.	export GOPATH=$HOME/go
e.	git clone https://github.com/projectatomic/docker-lvm-plugin.git
f.      make

First error it doesnt find github.com/Sirupsen/logrus

[root@apilibgdpr docker-lvm-plugin]# make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
main.go:8:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/golang/src/github.com/Sirupsen/logrus (from $GOROOT)
	/root/go/src/github.com/Sirupsen/logrus (from $GOPATH)
utils.go:14:2: cannot find package "github.com/docker/docker/pkg/system" in any of:
	/usr/lib/golang/src/github.com/docker/docker/pkg/system (from $GOROOT)
	/root/go/src/github.com/docker/docker/pkg/system (from $GOPATH)
driver.go:10:2: cannot find package "github.com/docker/go-plugins-helpers/volume" in any of:
	/usr/lib/golang/src/github.com/docker/go-plugins-helpers/volume (from $GOROOT)
	/root/go/src/github.com/docker/go-plugins-helpers/volume (from $GOPATH)
make: *** [lvm-plugin-build] Error 1

Please advise

**Comment by rocki9satya** [comment]
Thank you, it is working perfectly. 

I have one more question please. While creating a Docker LVM Volume with encryption is it possible to take the key from Docker Secrets.

E.g docker volume create --driver lvm --name example2 --opt size=100M --opt thinpool=volumes --opt crypt=luks --opt keyfile=/run/secrets/luks-volume-example.bin

I am unable to do so at present

**Comment by shishir-a412ed** [comment]
@rocki9satya I am not sure if they both are related. Better to create a separate LUKS secret file for `docker-lvm-plugin` encrypted volumes.
